
services:
  postgres:
    image: postgres:16
    container_name: shopster-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopster_users
      POSTGRES_USER: shopster_user
      POSTGRES_PASSWORD: shopster_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    networks:
      - shopster-network

  mongodb:
    image: mongo:7.0
    container_name: shopster-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: shopster_products_dev
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - shopster-network

  redis:
    image: redis:7-alpine
    container_name: shopster-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - shopster-network

  product-service:
    build:
      context: ./apps/product-service
      dockerfile: Dockerfile
    container_name: shopster-product-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/shopster_products_dev
    depends_on:
      - mongodb
    networks:
      - shopster-network

  user-service:
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile
    container_name: shopster-user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopster_users
      SPRING_DATASOURCE_USERNAME: shopster_user
      SPRING_DATASOURCE_PASSWORD: shopster_password
    depends_on:
      - postgres
    networks:
      - shopster-network

  membership-service:
    build:
      context: ./apps/membership-service
      dockerfile: Dockerfile
    container_name: shopster-membership-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopster_membership_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shopster_dev_password
    depends_on:
      - postgres
    networks:
      - shopster-network

  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    container_name: shopster-api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - product-service
      - user-service
      - membership-service
    networks:
      - shopster-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: shopster-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080
    depends_on:
      - api-gateway
    networks:
      - shopster-network

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  shopster-network:
    driver: bridge
