server:
  port: 8085
  servlet:
    context-path: /

spring:
  application:
    name: shopster-cart-service

  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 2000ms

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.shopster.cart: DEBUG
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  logging:
    level:
      root: INFO