server:
  port: 8084
  servlet:
    context-path: /

spring:
  application:
    name: shopster-membership-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shopster_membership_dev
    username: shopster_user
    password: shopster_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.shopster.membership: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/shopster_membership}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:shopster_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  logging:
    level:
      root: INFO