server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
        - id: user-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
        - id: cart-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/cart/**
        - id: membership-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/membership/**
